### PR TITLE
Upgrade to Go 1.21

### PR DESCRIPTION
**Pull request by daxmc99**

### CODE REVIEW

**Comment by daxmc99** [comment]
Will follow the release steps after merge

**Comment by varungandhi-src** [comment]
I tried updating this earlier but ran into test failures... https://github.com/sourcegraph/scip-go/pull/50

**Comment by varungandhi-src** [comment]
Closing this in favor of #50 as that updates all the relevant bits; there is a CI issue, I will look into that.

**Comment by daxmc99** [comment]
@varungandhi-src Thank you!

**Pull request closed without merging**
